services:
  postgres:
    image: postgres:16.2
    container_name: remix-auth-postgres
    ports:
      - "6500:5432"
    volumes:
      - remix-auth-postgres:/var/lib/postgresql/data
    env_file:
      - ./app/.env

volumes:
  remix-auth-postgres:
